# kubeship/manifests/base/ingress-cert.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeship-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  # Uncomment TLS when domain + certs are valid
  # tls:
  #   - hosts:
  #       - kubeship.celestn.dev
  #     secretName: tls-cert

  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-gateway
                port:
                  number: 80
