# kubeship/manifests/base/project.yaml

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubeship-project
  namespace: argocd
spec:
  description: KubeShip Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
