# kubeship/docker-compose.yml

services:
  nginx-gateway:
    build:
      context: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - auth-service

  auth-service:
    build: ./microservices/auth-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ITSD_RESET_SECRET=${ITSD_RESET_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - kubeship-pg-db

  kubeship-pg-db:
    image: postgres:latest
    container_name: kubeship-pg-db
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7
    container_name: kubeship-redis
    restart: unless-stopped
    ports:
      - "6379:6379"  

volumes:
  pgdata:
