# kubeship/helm-charts/redis/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
  selector:
    app: redis
