# kubeship/helm-charts/postgres-db/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "postgres-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "postgres-db.name" . }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: /kubeship/postgres
        property: POSTGRES_USER
        conversionStrategy: Default
        decodingStrategy: None        
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /kubeship/postgres
        property: POSTGRES_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None        
    - secretKey: POSTGRES_DB
      remoteRef:
        key: /kubeship/postgres
        property: POSTGRES_DB
        conversionStrategy: Default
        decodingStrategy: None        