# kubeship/helm-charts/postgres-db/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "postgres-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres-db
spec:
  refreshInterval: 5m
  deletionPolicy: Retain
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: /kubeship/postgres
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /kubeship/postgres
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: /kubeship/postgres
        property: POSTGRES_DB
