# kubeship/helm-charts/postgres-db/templates/secretstore.yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres-db
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "postgres-db.fullname" . }}-sa
            namespace: {{ .Release.Namespace }}
