# kubeship/helm-charts/postgres-db/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-db
