# kubeship/helm-charts/postgres-db/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
  selector:
    app: postgres-db
