# kubeship/helm-charts/postgres-db/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgres-db.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}