# kubeship/helm-charts/postgres-db/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ include "postgres-db.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
      statefulset.kubernetes.io/pod-name: {{ include "postgres-db.fullname" . }}
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      serviceAccountName: {{ include "postgres-db.fullname" . }}-sa
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
