# kubeship/manifests/external-secret.yaml
# This file defines an ExternalSecret resource that retrieves the database URL from AWS Secrets Manager.
# It is used by the auth-service to connect to the database securely.
# Ensure that the AWS Secrets Manager secret is created with the key /kubeship/auth/database_url

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-db-secret
spec:
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: auth-db-secret
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /kubeship/auth/database_url

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-secret
spec:
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: auth-secret
  data:
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: /kubeship/auth/jwt_secret
    - secretKey: REDIS_URL
      remoteRef:
        key: /kubeship/auth/redis_url