# kubeship/manifests/ingress.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeship-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
#  tls:
#    - hosts:
#        - kubeship.celestn.dev
#      secretName: tls-cert

  rules:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
