# kubeship/helm-charts/auth-service/values.yaml

replicaCount: 1

image:
  repository: 240398787204.dkr.ecr.eu-west-2.amazonaws.com/kubeship-auth-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8001
  targetPort: 8001

fullnameOverride: auth-service