# kubeship/helm-charts/auth-service/values.yaml

replicaCount: 1

image:
  repository: ""
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8001
  targetPort: 8001

env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: auth-db-secret
        key: DATABASE_URL

  - name: JWT_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: auth-secret
        key: JWT_SECRET_KEY

  - name: JWT_ALGORITHM
    value: "HS256"  

fullnameOverride: auth-service