# kubeship/helm-charts/nginx-gateway/values.yaml

replicaCount: 1

image:
  repository: "240398787204.dkr.ecr.eu-west-2.amazonaws.com/kubeship-nginx-gateway"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
