# kubeship/helm-charts/nginx-gateway/values.yaml

replicaCount: 1

namespace: nginx-gateway

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

fullnameOverride: nginx-gateway