# kubeship/helm-charts/frontend/values.yaml

replicaCount: 1

image:
  repository: ""
  tag:        "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

env:
  - name: VITE_API_URL
    value: /v1/auth

fullnameOverride: frontend