# kubeship/nginx/Dockerfile
# Added to test docker image push 1

# nginx Dockerfile
FROM nginx:1.25-alpine

# Copy custom config
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80
