# kubeship/helm-charts/auth-service/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "auth-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "auth-service.name" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    # now points at your cluster-wide store
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: {{ include "auth-service.fullname" . }}
    creationPolicy: Owner
    deletionPolicy: Retain    
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /kubeship/auth
        property: DATABASE_URL
        conversionStrategy: Default
        decodingStrategy: None        
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: /kubeship/auth
        property: JWT_SECRET_KEY
        conversionStrategy: Default
        decodingStrategy: None        
    - secretKey: REDIS_URL
      remoteRef:
        key: /kubeship/auth
        property: REDIS_URL
        conversionStrategy: Default
        decodingStrategy: None        
    - secretKey: JWT_ALGORITHM
      remoteRef:
        key: /kubeship/auth
        property: JWT_ALGORITHM
        conversionStrategy: Default
        decodingStrategy: None        