# kubeship/helm-charts/auth-service/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "auth-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth-service
spec:
  refreshInterval: 1m
  deletionPolicy: Retain
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: {{ include "auth-service.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /kubeship/auth
        property: DATABASE_URL
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: /kubeship/auth
        property: JWT_SECRET_KEY
    - secretKey: REDIS_URL
      remoteRef:
        key: /kubeship/auth
        property: REDIS_URL
    - secretKey: JWT_ALGORITHM
      remoteRef:
        key: /kubeship/auth
        property: JWT_ALGORITHM