# kubeship/helm-charts/auth-service/templates/namespace.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "auth-service.name" . }}
