# kubeship/helm-charts/auth-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/instance: {{ .Release.Name }}
