#.github/workflows/view-secrets-infra.yml

name: View Infrastructure Secrets (Debug Only)

on:
  workflow_dispatch:

jobs:
  show-infra-secrets:
    name: Show Infra Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Dump Infra Secrets to File
        run: |
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> secrets-infra.txt
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> secrets-infra.txt
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> secrets-infra.txt
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> secrets-infra.txt
          echo "TF_PROJECT_NAME=${{ secrets.TF_PROJECT_NAME }}" >> secrets-infra.txt
          echo "TF_ENVIRONMENT=${{ secrets.TF_ENVIRONMENT }}" >> secrets-infra.txt
          echo "TF_EKS_CLUSTER_NAME=${{ secrets.TF_EKS_CLUSTER_NAME }}" >> secrets-infra.txt
          echo "TF_STATE_BUCKET=${{ secrets.TF_STATE_BUCKET }}" >> secrets-infra.txt
          echo "TF_LOCK_TABLE=${{ secrets.TF_LOCK_TABLE }}" >> secrets-infra.txt
          echo "TF_GITOPS_REPO_URL=${{ secrets.TF_GITOPS_REPO_URL }}" >> secrets-infra.txt
          echo "TF_TARGET_REVISION=${{ secrets.TF_TARGET_REVISION }}" >> secrets-infra.txt
          echo "TF_ARGOCD_APP_MANIFEST_PATH=${{ secrets.TF_ARGOCD_APP_MANIFEST_PATH }}" >> secrets-infra.txt
          echo "TF_AVAILABILITY_ZONE_1=${{ secrets.TF_AVAILABILITY_ZONE_1 }}" >> secrets-infra.txt
          echo "TF_AVAILABILITY_ZONE_2=${{ secrets.TF_AVAILABILITY_ZONE_2 }}" >> secrets-infra.txt
          echo "AWS_ACCESS_KEY_ID_ARN=${{ secrets.AWS_ACCESS_KEY_ID_ARN }}" >> secrets-infra.txt

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
