# kubeship/helm-charts/nginx-gateway/templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }

    http {
    include       mime.types;
    default_type  application/json;
    sendfile      on;
    keepalive_timeout 65;

    # health probe for k8s / cert-manager
    server {
        listen 80;
        server_name _;
        root   /usr/share/nginx/html;
        index  index.html;

        location = /health {
        return 200 'OK';
        add_header Content-Type text/plain;
        }

        # ACME HTTP-01 challenge
        location ^~ /.well-known/acme-challenge/ {
        alias /usr/share/nginx/html/.well-known/acme-challenge/;
        default_type "text/plain";
        }

        # proxy to auth-service
        location /v1/auth/ {
        proxy_pass         http://auth-service.auth-service.svc.cluster.local:8001;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_read_timeout    90;
        proxy_connect_timeout 90;
        }

        # → add more microservices as you grow:
        # location /v1/payments/ { proxy_pass http://payments:80; … }

        # all other traffic → React SPA
        location / {
        try_files $uri $uri/ @spa;
        }
        location @spa {
        internal;
        rewrite ^ /index.html break;
        }

        # friendly errors
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        root /usr/share/nginx/html;
        }
      }
    }
