# kubeship/helm-charts/nginx-gateway/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: {{ .Values.service.type }}